name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
